### PR TITLE
deps(algonaut_transaction): bump serde_bytes 0.11 → 0.11.4

### PR DESCRIPTION
**Pull request by PiDelport**
serde_bytes 0.11.4 adds support for bytes inside of Option, which `algonaut_transaction::api_model::ApiTransaction` depends on.

* https://github.com/serde-rs/bytes/releases/tag/0.11.4

### CODE REVIEW

**Comment by ivanschuetz** [comment]
Hi, thanks for the PR! Can you please explain how exactly this affects our code? We're using `with = "serde_bytes"` on several optional byte vectors in `ApiTransaction`. Is something not working 🤔?

**Comment by PiDelport** [comment]
@ivanschuetz: This shouldn't affect any code using this library with serde_bytes 0.11.4 or later.

The effect is mainly to have a more actionable error message if someone tries to build it with serde_bytes 0.11.0–0.11.3: previously, this would result in a somewhat opaque missing trait implementation compilation error; with this bump, cargo will give a more clear and actionable version conflict error.

(We ran into this downstream, with serde_bytes 0.11.3.)

**Comment by ivanschuetz** [comment]
Ah I get it! I'm new to maintaining Rust libraries. I assumed (aside of shortly forgetting that this is a library :p) that updating a dependency downstream (via the cargo.toml) does something like `cargo update` for the transitive dependencies, which would pull in compatible versions, but I guess that it's more conservative. Any recommendations to help avoiding this issue (aside of "remembering" to bump the version when using the new feature)?

**Comment by PiDelport** [comment]
I think in this case, to stay SemVer-compatible, serde_bytes should actually have bumped their minor version for the new trait impls, since they represent new functionality: in other words, 0.11.4 might better have been 0.12.0.

**Comment by ivanschuetz** [comment]
Right, they weirdly just updated the patch version. I think I was remembering this part of the cargo book:

> Try to keep the dependency versions up-to-date with the actual minimum versions that your library requires. For example, if you have a requirement of bar="1.0.12", and then in a future release you start using new features added in the 1.1.0 release of "bar", update your dependency requirement to bar="1.1.0".

> If you fail to do this, it may not be immediately obvious because Cargo can opportunistically choose the newest version when you run a blanket cargo update. However, if another user depends on your library, and runs cargo update -p your-library, it will not automatically update "bar" if it is locked in their Cargo.lock. It will only update "bar" in that situation if the dependency declaration is also updated. Failure to do so can cause confusing build errors for the user using cargo update -p.

In this (edge?) case (if the major version is > 0, which isn't the case here) it would have been not enough if they updated the minor version. 

I'm not sure anyway how the dependency update compares when running `build` (which you might have been used) vs `update`.

I'll stop now misusing this PR for these clarifications!

**Pull request merged**
